# Generated by Django 5.1.3 on 2024-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.AddField(
            model_name='assignment',
            name='markscheme',
            field=models.FileField(default='', upload_to='marksheets/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_files',
            field=models.FileField(default='', upload_to='student_pdfs/'),
            preserve_default=False,
        ),
    ]
