# Generated by Django 5.1.3 on 2024-11-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_assignment_project_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='markscheme',
            field=models.FileField(blank=True, null=True, upload_to='markschemes/'),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student_files',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_file', models.FileField(upload_to='student_works/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to='main.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='student_files',
            field=models.ManyToManyField(related_name='assignments', to='main.studentwork'),
        ),
    ]
