# Generated by Django 5.1.3 on 2024-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_assignment_markscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentwork',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student_files',
            field=models.ManyToManyField(related_name='related_assignments', to='main.studentwork'),
        ),
    ]
