# Generated by Django 5.1.3 on 2024-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_assignment_is_group_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='group_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
