# Generated by Django 5.1.3 on 2024-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
