# Generated by Django 5.1.3 on 2024-11-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_feedback_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mark',
            field=models.FloatField(),
        ),
    ]
