# Generated by Django 5.1.3 on 2024-11-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_feedback_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentwork',
            name='student_file_path',
            field=models.CharField(default='sui', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='markscheme',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
