# Generated by Django 5.1.3 on 2024-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_assignment_markscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwork',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
