# Generated by Django 5.1.3 on 2024-12-02 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studentwork_is_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentwork'),
        ),
    ]
