# Generated by Django 5.1.3 on 2025-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_studentmark_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='custom_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
