# Generated by Django 5.1.3 on 2025-03-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_studentmark_custom_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.feedback'),
        ),
    ]
