# Generated by Django 5.1.3 on 2025-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_studentmark_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='custom_mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
